name: PHPUnit for PHPStan issues

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  enable_cli_with_swoole:
    name: Test for PHPStan with Swoole and Opcache enable cli
    runs-on: 'ubuntu-latest'
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      SW_VERSION: 'v4.8.1'
    strategy:
      matrix:
        php-version: [ '8.0' ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=1
          coverage: none
      - name: Setup Swoole
        run: ./.github/swoole.install.sh
      - name: Run Test Cases
        run: |
          cd phpstan/enable_cli_with_swoole
          composer update -o
          vendor/bin/phpstan analyse -l 5 -c phpstan.neon index.php
